# Default values for static k8s file.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Pass your k8s static file here (for instance a secret)
static: |
  apiVersion: v1
  kind: Secret
  metadata:
    name: mysecret
  type: Opaque
  data:
    username: YWRtaW4=
    password: MWYyZDFlMmU2N2Rm